apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user1
spec:
  groups:
    - system:authenticated
  request: $(cat user1-base64.csr)
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 864000
  usages:
    - client auth