apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: development-role
  namespace: development
subjects:
  - kind: User
    name: developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: development-role
  apiGroup: rbac.authorization.k8s.io