apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: development-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "patch", "get", "list", "watch"]